# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf
        args: ['--style', '{based_on_style: pep8; indent_width: 4}']

-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'  # Use the sha / tag you want to point at
    hooks:
    -   id: flake8
        args: ['--ignore=F401,E501,W503,W504,W605,E125,E129,E502,E128,E402']

-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: bandit
        args: ['--level', 'LOW']

-   repo: https://github.com/twu/skjold
    rev: 'v0.2.1'
    hooks:
    -   id: skjold
        args: ['-s', 'gemnasium', '-s', 'pyup']

-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
