version: '3.8'

services:
    db:
        volumes:
          - /home/postgis-docker/django-futils/dev/data:/var/lib/postgresql/data
    web:
        volumes:
          - ./db/dev/data:/code/django/data

        ports:
            - 3050:3050

        environment:
            - DJANGO_ENV=development
