"""
Django settings for grantme project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _
import django_futils.constants as const

SECRET_KEY='a'

NOMINATIM_URL = 'https://nominatim.openstreetmap.org'

# 6 months = 60 * 60 * 24 * 30 * 6
NOMINATIM_CACHE_TTL_SECONDS = 15552000

OPENLAYERS_URL = 'https://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/OpenLayers.js'

# Set this integer appropriately.
STARTING_INVOICE_ID_OF_CURRENT_YEAR = 0

# The way foreign keys and onetoone fields are displayed.
# 0=default
# 1=raw
# 2=autocomplete
FOREIGN_KEY_FIELDS = 1

# Validate the custom secret settings.
if not isinstance(NOMINATIM_URL, str):
    raise TypeError
if not isinstance(NOMINATIM_CACHE_TTL_SECONDS, int):
    raise TypeError
if not isinstance(OPENLAYERS_URL, str):
    raise TypeError
if not isinstance(FOREIGN_KEY_FIELDS, int):
    raise TypeError
if NOMINATIM_CACHE_TTL_SECONDS <= 0:
    raise ValueError
if FOREIGN_KEY_FIELDS != const.FOREIGN_KEY_FIELDS_DEFAULT and FOREIGN_KEY_FIELDS != const.FOREIGN_KEY_FIELDS_RAW and FOREIGN_KEY_FIELDS != const.FOREIGN_KEY_FIELDS_AUTOCOMPLETE:
    raise ValueError

# django-simple-history
SIMPLE_HISTORY_REVERT_DISABLED = True

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

LANGUAGES = [
    ('it', _('Italian')),
    ('en', _('English')),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'simple_history',
    'vies',
    'phone_field',
    'django_countries',
    'django.contrib.gis',
    'djmoney',
    'django_extensions',
    'django_futils.apps.DjangoFutilsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]

#ROOT_URLCONF = 'grantme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django_admin_env_notice.context_processors.from_settings',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'django_futils/static'),
]
